### ISSUE TITLE
What can I help with?

### ISSUE THREAD

**Issue by HittmanA** [NetherManiacsKingdom/WorkingInProgres-Plugins-sourcecode-for-dev#1]

**Comment by NetherOwner** [comment]
With making email.php in enderauth

**Comment by HittmanA** [comment]
I DON'T UNDERSTAND WHAT YOU WANT WITH IT! What is it supposed to do?

**Comment by Edwardthedog2** [comment]
I do need some more help with SAM @HittmanA. I need help merging the MainClass.php file, and the web.php file (code that connects pocketmine with website) into one file, so maybe it will work.

**Comment by HittmanA** [comment]
Ok ill see what i can do!

**Comment by flaxues** [comment]
If you want mail you have to get a mail server or something

**Comment by DavidJBrockway** [comment]
I have mail servers with go daddy
