### ISSUE TITLE
SAM

### ISSUE THREAD

**Issue by HittmanA** [NetherManiacsKingdom/WorkingInProgres-Plugins-sourcecode-for-dev#2]
edward how do you want web.php transferred to main.php?

**Comment by HittmanA** [comment]
@Edwardthedog2 i made a new branch with updated code. See if it will work.

**Comment by Edwardthedog2** [comment]
Okay

**Comment by HittmanA** [comment]
Does it look like it works @Edwardthedog2 ?

**Comment by Edwardthedog2** [comment]
Nope, it crashed the server.

**Comment by HittmanA** [comment]
Hmmm i will look into it. Can i have the crash dump also plz?

**Comment by Edwardthedog2** [comment]
Yes here it is:

[CrashDump.txt](https://github.com/NetherManiacsKingdom/WorkingInProgres-Plugins-sourcecode-for-dev/files/147381/CrashDump.txt)

**Comment by HittmanA** [comment]
k thanks!
