### ISSUE TITLE
 Lucky Blocks Plugin Crashess When Server Boots Up!

### ISSUE THREAD

**Issue by matthew4444** [NetherManiacsKingdom/WorkingInProgres-Plugins-sourcecode-for-dev#3]
PLZ FIX,PUT LOCKY BLOCKS IN UR SERVER,AND FIND THE BUG IN THE CRASH DUUMP U GET!!!!!!!!!!!!!!!! PLZ FIX!!!!!!!

**Comment by matthew4444** [comment]
GTG FORA COUPLE OF HOURS SRRY! from matthew4444

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
can i get the crash dump

**Comment by matthew4444** [comment]
u need to copile lucky blocks and boot it on ur server and get the crash dump from it,due to im not on my tablet with the crash dump on right now
srry

**Comment by NetherOwner** [comment]
Dont past issus on enderauth put it on lucky block this is only for enderauth issus!

**Comment by matthew4444** [comment]
Hey

**Comment by NetherOwner** [comment]
Hey

**Comment by NetherOwner** [comment]
Go on gitter

**Comment by matthew4444** [comment]
Ok
