### ISSUE TITLE
EdWard i need help

### ISSUE THREAD

**Issue by NetherOwner** [NetherManiacsKingdom/WorkingInProgres-Plugins-sourcecode-for-dev#4]
# Hey EdWard i saw your AuthMePE and i saw there was something with mail like a email.php can you make that on the EnderAuth we relly need email.php plss help me

**Comment by Edwardthedog2** [comment]
Yes, I can help.

**Comment by matthew4444** [comment]
Ok

**Comment by NetherOwner** [comment]
Yay thank you edward

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
http://nmk.navhost.com/startbootstrap-heroic-features-1.0.4/startbootstrap-heroic-features-1.0.4/index.html.new.html Im working on site lol

**Comment by matthew4444** [comment]
Alsmost done with galdiormine site

**Comment by DavidJBrockway** [comment]
i would but have been kicked why

**Comment by DavidJBrockway** [comment]
why you removed me i cant update plugins or make them
